### ISSUE TITLE
"List possible moves" wrong in documentation

### ISSUE THREAD

**Issue by conema** [anzemur/chess-api#1]
In the documentation is not indicated that the "list possible moves" request should have the game_id on the request body.
[Link to the API page](https://documenter.getpostman.com/view/1741165/chess-api/7Lof2bk#1356574c-ca8f-0f56-71a9-531fb6b0b823)

Is there a simple way to know the pieces name by their location?

Thanks for your work!

**Comment by anzemur** [comment]
Hello,
yes I should add this to the docs. But in general every request that is connected to the specific game should have game_id as the parameter. 

Currently there is no route implemented for getting single piece by its location on the board, but it can be easly implemented into the api usign [chess.js](https://github.com/jhlywa/chess.js/blob/master/README.md) .get(square) method.

A complete more robust rewrite with some additional options of the api should happen in the fututre if I have some spare time.

Best regards,
Anze
